variables:
    GIT_SSL_NO_VERIFY: "1"
before_script:   
        - echo $CI_REPOSITORY_URL   
        - echo $HOSTNAME   
        - echo $USER   
        - echo $PWD 
Install:  
  script:
       - cd src
       - make clean
       - make
       - make check


